export const sampleStudents = [
    { id: 1, name: 'John', attendance: 0.91, hours: 14, prev: 78, parent: 'High', online: true, final: 82 },
    { id: 2, name: 'Aisha', attendance: 0.72, hours: 6, prev: 55, parent: 'Low', online: false, final: 46 },
    { id: 3, name: 'Meera', attendance: 0.96, hours: 18, prev: 88, parent: 'Medium', online: true, final: 92 },
    { id: 4, name: 'Karthik', attendance: 0.80, hours: 10, prev: 60, parent: 'Medium', online: false, final: 58 },
    { id: 5, name: 'Lina', attendance: 0.65, hours: 4, prev: 50, parent: 'Low', online: true, final: 38 },
    { id: 6, name: 'Ravi', attendance: 0.88, hours: 12, prev: 72, parent: 'High', online: false, final: 75 },
    { id: 7, name: 'Sara', attendance: 0.78, hours: 8, prev: 58, parent: 'Medium', online: true, final: 60 },
    { id: 8, name: 'Tom', attendance: 0.92, hours: 15, prev: 80, parent: 'High', online: false, final: 85 },
    { id: 9, name: 'Nina', attendance: 0.70, hours: 5, prev: 52, parent: 'Low', online: true, final: 42 },
    { id: 10, name: 'Ali', attendance: 0.85, hours: 11, prev: 68, parent: 'Medium', online: false, final: 70 },
    { id: 11, name: 'Maya', attendance: 0.60, hours: 3, prev: 45, parent: 'Low', online: true, final: 30 },
    { id: 12, name: 'Omar', attendance: 0.89, hours: 13, prev: 74, parent: 'High', online: false, final: 78 },
    { id: 13, name: 'Zara', attendance: 0.95, hours: 17, prev: 85, parent: 'Medium', online: true, final: 90 },
    { id: 14, name: 'Leo', attendance: 0.75, hours: 7, prev: 57, parent: 'Low', online: false, final: 50 },
    { id: 15, name: 'Eva', attendance: 0.82, hours: 9, prev: 62, parent: 'Medium', online: true, final: 65 },
    { id: 16, name: 'Sam', attendance: 0.68, hours: 4, prev: 48, parent: 'Low', online: false, final: 35 },
    { id: 17, name: 'Lily', attendance: 0.90, hours: 14, prev: 77, parent: 'High', online: true, final: 80 },
    { id: 18, name: 'Jake', attendance: 0.73, hours: 6, prev: 54, parent: 'Low', online: false, final: 45 },
    { id: 19, name: 'Nora', attendance: 0.94, hours: 16, prev: 86, parent: 'Medium', online: true, final: 88 },
    { id: 20, name: 'Max', attendance: 0.81, hours: 10, prev: 61, parent: 'Medium', online: false, final: 60 },
]
